language: java
jdk: openjdk8
deploy:
  provider: heroku
  api_key:
    secure: ZGGCvK03NR6EyG/0uJZF7nx1qThVjSg+KgejANo1f4gfItCY8/1Jov+KN9nCNKn/wZDwmgh4+ITdsq0u70aU3BHAhdeeForJjLVmK2CfH/q8wW5+kU3DE8o1Fl42GwK30iV96sRduUXCr7AsObGyDqtyFwuUVDOcAaCGQvPmK+q9wTVqNw55jGcrQ4KcIE0HPvYCwx+Vok7ScQk6av9cKGPlxVZJ/98VqUjB0YAvg/wv+WujN1aSWdo3HJ58XHMy7+GWcNIlQUtWgmPIOaeqt8bhqR0zw1e0SB63a1pEv9bRaNHnG4YeSkHuFwkqZyDfp1U3BB59ApbDqkHVDq9yzDrHlRSQrc9smETWFkG1NNkAB7X9a/ptrN5VbHE8mafbmfMUTDTnMB1K1TFnWnRO0vJzxQtjwM7dYSGESYj6phlJRdVVww9GIcRq3WbyfW87a5R6/Woz5ADJzuBsrqhdtG8geD9kin0c8trRbmR8bYBa+R7btOXRjFb/lHAiKg6ZOzlcWXzVkD5FM8E8vwv+5viocxTLF/q+d37SOUHeSw6WQ2FT4w7GKDlJjCM2iLUhi8TbYm8EUU4HEuL3EfTBAvLJwv2RT072978KgXhI+tJvkzuoqMNA/BYocReyPrJZ803yGy8c3VofHlqEoghcDoHdVucaqQw0O7Vw+RaBXL4=
